### ISSUE TITLE
Cannot locate 'padsystem' gem

### ISSUE THREAD

**Issue by daveshenk** [stakach/em_control#2]
Not sure where to find the 'padsystem' gem. It looks like it's mostly geared at AMX gear, which I don't have so I commented it out of the gemfile as a workaround.

**Comment by stakach** [comment]
That is to do with the interface for controlling the system.
Every interface is a HTML5 web page that is defined as a mountable rails 3.1 engine.

We use the pad system for internal testing, however is actually just the university of Sydney's collaboration interface. Designed to run on an iPad in web application mode.
See here: http://dl.dropbox.com/u/30774132/ipadiface/usyd-pod.html

All will be explained in the tutorial. Personally I'd use jquery mobile for interface construction, I'll provide a working example tomorrow.

**Comment by stakach** [comment]
Also these Are good interface development tools

http://labs.adobe.com/technologies/edge/
http://googlecode.blogspot.com/2011/06/swiffy-convert-swf-files-to-html5.html
http://tumultco.com/hype/
http://www.appmobi.com/
http://www.purpleanimator.com/

We use Hype at the moment, although we are going to give purple a go soon

**Comment by daveshenk** [comment]
It's starting to make more sense to me. I'll be looking forward to the tutorial. 

I had not heard of the Purple app, but it looks intriguing for certain uses.

**Comment by stakach** [comment]
@daveshenk I wrote lots of documentation today and updated most of the wiki to be more or less up to date.

The main stuff is under the How it works section of the [wiki](https://github.com/stakach/em_control/wiki)
It's still probably a little much to get your head around so I'm building a demo interface with its own wiki on how to get everything running (a lot simpler than I've probably made it out to be)

The demo system can be used as the starting point for future systems until we build a rails like generator.

**Comment by stakach** [comment]
Hi Dave, sorry it took me a little longer than I expected to write up the demo interface for you.
Should be fairly easy to get a grip on. It can be found here with integration instructions: [https://github.com/stakach/Example-Control-Interface](https://github.com/stakach/Example-Control-Interface)

Also this is what the final result will look like: [http://dl.dropbox.com/u/30774132/meeting-room-interface/interface%20projector.html](http://dl.dropbox.com/u/30774132/meeting-room-interface/interface%20projector.html)

and a simpler one

[http://dl.dropbox.com/u/30774132/meeting-room-interface/interfaceLCD.html](http://dl.dropbox.com/u/30774132/meeting-room-interface/interfaceLCD.html)

**Comment by stakach** [comment]
I also wrote up a quick bit on authentication and how this relates to accessing control systems from their interfaces:
[https://github.com/stakach/em_control/wiki/Authentication-and-users](https://github.com/stakach/em_control/wiki/Authentication-and-users)

**Comment by stakach** [comment]
This will be resolved in full later
