### ISSUE TITLE
Controller Devices/Add New error in rails_admin

### ISSUE THREAD

**Issue by daveshenk** [stakach/em_control#4]
I'm able add Users, System and Zones. When I try to add a new device I get the following;

Showing /Users/daveshenk/.rvm/gems/ruby-1.9.3-p0/bundler/gems/rails_admin-be59419f362e/app/views/layouts/rails_admin/_secondary_navigation.html.haml where line #3 raised:

undefined method `actual_name' for nil:NilClass

Looking at the file, it seems like this is the snippet it doesn't like
wording_for(:menu, action) 

I tried commenting it out and got errors in application.html.haml at line 35
menu_for((@abstract_model ? (@object.try(:id) ? :member : :collection) : :root), @abstract_model, @object)

**Comment by daveshenk** [comment]
Maybe it's because I'm using sqlite3... Installing postgres to see

Edit: nope, same deal with PostgreSQL

**Comment by daveshenk** [comment]
Which version of rails_admin are you using? It looks like they've recently starting using localization files, maybe that's the problem?

**Comment by daveshenk** [comment]
tracked it down to config/initializers/rails_admin.rb line 334

def dev_label_method
  "#{self.dependency.actual_name} instance"
end

I commented out, page loads, and I don't see word instance show up anywhere.

**Comment by stakach** [comment]
Also fixed this in the trunk.
Didn't happen with older versions of rails admin, probably shouldn't be using the edge version.
