### ISSUE TITLE
Samsung LCD

### ISSUE THREAD

**Issue by daveshenk** [stakach/em_control#6]
Not an issue so much as a question. Which Samsung LCD model are you using that has IP control? Smart TV?

**Comment by stakach** [comment]
Hi Dave,

Actually I created a new project that packages control as a gem. Sort of an extension to rails which is much easier to work with, namespaces things better and fixes many bugs: https://github.com/stakach/automate-em

I'm not sure if the current version is on rubygems yet (I'll do that tomorrow at work) however you can point your gem file directly at the trunk (I'll be keeping that stable)

It changes the way modules are defined slightly. There is quite a bit of documentation already up and I'll add more soon / I should create a repository for modules (so there are more examples)

http://www.samsunglfd.com/product/spec.do?modelCd=460DX-3
That is the particular display that the module was developed for, however I believe it is standardised across their range.

**Comment by daveshenk** [comment]
Nice work on automate-em! I know you'd mentioned you were going to package it all up as a gem, it's great to see that you did.

**Comment by stakach** [comment]
If you send me an email I'll send through the updated modules and a bit more documentation on how to register modules. I haven't had time to create a project to host them

Just follow the links on my website (about -> Stephen etc)
